Multiverse NFT is a new concept of NFTs where character image combinations are being sell rather than unique character images. Our aim is to protect the underlying asset of NFTs while at the same time provide awareness to the public what people are actually buying.

Whenever people ask us why we buy NFTs. There are different level of explanations that are being provided. From the very complex one which is about exclusivity and economy explanations up until the most simple conversation like the following:
Person A: Why you buy this NFT? I can easily steal its image by simply right clicking it. That's so dumb.
Person B: So you steal my NFT huh?! Try sells it at OpenSea then...
Which technically speaking the statement is not wrong, but maybe not good enough. A secret source is lacking.

The question is, Why Don't We Just Make Them Unable To Steal It Completely?

Take the following 2 images as examples. The 1 in the left is called ADAM whereas the 1 in the right is called EVE. They both represent 2 exclusive NFTs for the first batch of Multiverse NFTs which are not for selling. Now, try and download them into your own computer. Great, now try refreshing the page. Did you see any differences between them with the images you just downloaded? Correct, they are not the same. You can try to do the same thing again and again, and yes if you are lucky enough, you will get the same image, but that's not the whole point of this form of NFTs.

Why these NFTs are not the same? This is because each Multiverse have more than 1 what we called the state. Take ADAM as example, it has 25 states, which also means if you want to "Steal" this NFT, you need to first at least refresh this page 25 times and you need to be lucky enough to get all unique states of the collection after that find a way to combine them so that you are not wasting your local memory spaces. Pretty cool wasn't it? The EVE here has only 12 states, but unlike ADAM which is originated from 1 single image, EVE originated from a custom number of images upload by creators, in this case is us. This show the potentials on how the Multiverse NFTs can change the perspectives of people who buy any NFT, we are not buying the underlying asset actually, we are buying the credits promised by the sellers, the exclusivity provided by the creators, the perspectives shared by the community, and this is what an NFT is, it is a code, on chain.

Why we choose this approach?
Nowadays, NFT projects usually consist of 10k unique character images. This model is great in a sense it differentiate itself with coins because NFTs are Non Fungible. But they have 2 main problems, 1) too many unique character images which made the burden on artists heavy when converting them into new forms (e.g converting pixel arts to 3D arts, making live 2d models, can you really change each buyers' arts 1 by 1?) Our project tackle this problem by introducing less variant of the unique art pieces while also introducing a new way to differentiate them 1 and another 2) when too many uniqueness involve, the model they can possibly represent in other fields reduce (e.g imagine a system where different traits represent different tables you can use, as an implementer you might need to prepare many variants, yet reducing traits = reducing total NFTs count) Our project inspired by other games concept which introducing similar variations count to each NFT owners, this can create a fairness among the game OR any medium created since every NFT owner will have similar active NFT triggered at a time

GENESIS can use those 6 characters
COUPLE can use all but the core 2 characters must remain active, they can choose the other 4 at ease



The first batch of Multiverse NFTs consist of 1005 .
We break down each batch of Multiverse NFTs into different problem that we try to solve and tokens generated by these NFTs represent credits for using those systems for free. So please invest only if the system is useful for you. You can still support us in many other ways and we are welcoming supporters from any field or location because one of the main benefits of being on chain is decentralize anyway.

Please dun fomo into the project if you dun know what you are doing, yes these NFTs will generate another coins for their buyers, but please reconsider because this idea is still very new. However we do reward out supporters with our ways. At the end, it is up you the public decide whether this project creates any value.
